// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account.proto

package accountmgr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Response struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{3}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "accountmgr.Empty")
	proto.RegisterType((*Account)(nil), "accountmgr.Account")
	proto.RegisterType((*Response)(nil), "accountmgr.Response")
	proto.RegisterType((*Token)(nil), "accountmgr.Token")
	proto.RegisterType((*Error)(nil), "accountmgr.Error")
}

func init() { proto.RegisterFile("proto/account.proto", fileDescriptor_477cbf5ae5b46edf) }

var fileDescriptor_477cbf5ae5b46edf = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x6d, 0x93, 0x26, 0xed, 0x37, 0xe5, 0x13, 0x9c, 0xf6, 0x10, 0x7a, 0x2a, 0x7b, 0xaa, 0x07,
	0xab, 0x44, 0x44, 0x3c, 0x78, 0x28, 0x52, 0x7a, 0xf2, 0x12, 0xc4, 0xa3, 0xb0, 0x26, 0x43, 0x0d,
	0x26, 0xd9, 0xb0, 0xd9, 0x2a, 0xfe, 0x11, 0x7f, 0xaf, 0xec, 0x24, 0xb5, 0x29, 0xe6, 0xe2, 0x6d,
	0xdf, 0xdb, 0x99, 0x37, 0x6f, 0xde, 0x2e, 0x4c, 0x4a, 0xad, 0x8c, 0xba, 0x90, 0x71, 0xac, 0x76,
	0x85, 0x59, 0x32, 0x42, 0x68, 0x60, 0xbe, 0xd5, 0x62, 0x08, 0xde, 0x3a, 0x2f, 0xcd, 0xa7, 0xd8,
	0xc1, 0x70, 0x55, 0xd3, 0x78, 0x02, 0x4e, 0x9a, 0x04, 0xfd, 0x79, 0x7f, 0xf1, 0x2f, 0x72, 0xd2,
	0x04, 0x11, 0x06, 0x85, 0xcc, 0x29, 0x70, 0x98, 0xe1, 0x33, 0x4e, 0xc1, 0xa3, 0x5c, 0xa6, 0x59,
	0xe0, 0x32, 0x59, 0x03, 0x9c, 0xc1, 0xa8, 0x94, 0x55, 0xf5, 0xa1, 0x74, 0x12, 0x0c, 0xf8, 0xe2,
	0x07, 0xdb, 0x0e, 0xa3, 0xde, 0xa8, 0x08, 0xbc, 0xba, 0x83, 0x81, 0xb8, 0x85, 0x51, 0x44, 0x55,
	0xa9, 0x8a, 0x8a, 0xf0, 0x1c, 0x86, 0x8d, 0x33, 0x1e, 0x3e, 0x0e, 0x27, 0xcb, 0x83, 0xd3, 0x65,
	0xe3, 0x2e, 0xda, 0xd7, 0x88, 0x67, 0xf0, 0x1e, 0xad, 0xc6, 0x41, 0xb9, 0xdf, 0x52, 0xb6, 0xec,
	0xbb, 0xcc, 0xd2, 0x84, 0x6d, 0x8f, 0xa2, 0x1a, 0xe0, 0x19, 0xf8, 0xa4, 0xb5, 0xd2, 0x55, 0xe0,
	0xce, 0xdd, 0xc5, 0x38, 0x3c, 0x6d, 0x8f, 0x58, 0xdb, 0x9b, 0xa8, 0x29, 0x10, 0x77, 0xe0, 0x31,
	0x61, 0xf7, 0x8f, 0x55, 0x42, 0x2c, 0xef, 0x45, 0x7c, 0xc6, 0x39, 0x8c, 0x13, 0xaa, 0x62, 0x9d,
	0x96, 0x26, 0x55, 0x45, 0x13, 0x4d, 0x9b, 0x0a, 0xbf, 0x1c, 0x80, 0xc6, 0xf3, 0xc3, 0x56, 0xe3,
	0x35, 0xf8, 0xf7, 0x9a, 0xa4, 0x21, 0xec, 0xda, 0x6a, 0x36, 0x6d, 0x93, 0xfb, 0x44, 0x44, 0x0f,
	0x43, 0x70, 0x37, 0x64, 0xfe, 0xda, 0xe3, 0x6f, 0xc8, 0xac, 0xb2, 0x0c, 0x8f, 0xb7, 0xb3, 0xef,
	0x3c, 0xeb, 0x52, 0x12, 0x3d, 0xbc, 0x84, 0xc1, 0x6a, 0x67, 0x5e, 0xbb, 0x07, 0x1d, 0xc9, 0x70,
	0xe6, 0xa2, 0x87, 0x37, 0xf0, 0xff, 0xc9, 0x46, 0x2a, 0x0d, 0xd5, 0xcf, 0xf0, 0xbb, 0xaa, 0xb3,
	0xf1, 0xc5, 0xe7, 0x5f, 0x78, 0xf5, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xca, 0x53, 0x3c, 0xce, 0x9c,
	0x02, 0x00, 0x00,
}
