# docker-compose.yaml
version: '3.7'

services:

  broker:
    image: rabbitmq:management
    container_name: dccn-broker-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  datastore:
    image: mongo:latest
    container_name: dccn-mongo
    ports:
      - "27017:27017"

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  micro:
    image: microhq/micro:latest
    command: --enable_stats --register_interval=5 --register_ttl=10 --register_interval=10 app-dccn-api --handler=rpc
    links:
      - consul
    ports:
      - "8080:8080"

  taskmgr:
    image: app-dccn-taskmgr
    container_name: app-dccn-taskmgr
    build:
      context: .
      dockerfile: ./dockerfile/task.Dockerfile
    environment:
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: consul:8500
      MICRO_BROKER: rabbitmq
      MICRO_BROKER_ADDRESS: amqp://guest:guest@broker:5672
      MICRO_SERVER_VERSION: v1.0
      MICRO_REGISTER_INTERVAL: 15
      DB_HOST: datastore:27017
      DB_NAME: dccn
      DB_COLLECTION: task
      DB_TIMEOUT: 5
      DB_POOL_LIMIT: 4096
      DISABLE_AUTH: "true"
    links:
      - broker
      - datastore
      - consul

  usermgr:
    image: app-dccn-usermgr
    container_name: app-dccn-usermgr
    build:
      context: .
      dockerfile: ./dockerfile/user.Dockerfile
    environment:
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: consul:8500
      MICRO_BROKER: rabbitmq
      MICRO_BROKER_ADDRESS: amqp://guest:guest@broker:5672
      MICRO_SERVER_VERSION: v1.0
      MICRO_REGISTER_INTERVAL: 15
      DB_HOST: datastore:27017
      DB_NAME: dccn
      DB_COLLECTION: user
      DB_TIMEOUT: 5
      DB_POOL_LIMIT: 4096
    links:
      - datastore
      - consul

  email:
    image: app-dccn-email
    container_name: app-dccn-email
    build:
      context: .
      dockerfile: ./dockerfile/email.Dockerfile
    environment:
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: consul:8500
      MICRO_BROKER: rabbitmq
      MICRO_BROKER_ADDRESS: amqp://guest:guest@broker:5672
      MICRO_SERVER_VERSION: v1.0
      MICRO_REGISTER_INTERVAL: 15
      DB_HOST: datastore:27017
      DB_NAME: dccn
      DB_COLLECTION: user
      DB_TIMEOUT: 5
      DB_POOL_LIMIT: 4096
    links:
      - broker
      - datastore
      - consul

  api:
    image: app-dccn-api
    container_name: app-dccn-api
    build:
      context: .
      dockerfile: ./dockerfile/api.Dockerfile
    environment:
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: consul:8500
      MICRO_SERVER_ADDRESS: :50051
      MICRO_BROKER: rabbitmq
      MICRO_BROKER_ADDRESS: amqp://guest:guest@broker:5672
      MICRO_SERVER_VERSION: v1.0
      MICRO_REGISTER_INTERVAL: 15
      DB_HOST: datastore:27017
      DB_NAME: dccn
      DB_COLLECTION: datacenter
      DB_TIMEOUT: 5
      DB_POOL_LIMIT: 4096
      DISABLE_AUTH: "true"
    ports:
      - "50051:50051"
    links:
      - taskmgr
#      - email
      - usermgr
      - broker
      - datastore
      - consul

#  all:
#    image: app-dccn-all-test
#    container_name: app-dccn-all-test
#    build:
#      context: .
#      dockerfile: ./dockerfile/test.Dockerfile
#    environment:
#      API_ADDRESS: api:50051

  register:
    image: app-dccn-register
    container_name: app-dccn-register
    build:
      context: .
      dockerfile: ./dockerfile/register.Dockerfile
    environment:
      API_ADDRESS: api:50051

#  task-client:
#    image: app-dccn-task-client
#    container_name: app-dccn-task-client
#    build:
#      context: .
#      dockerfile: ./dockerfile/task_client.Dockerfile
#    environment:
#      API_ADDRESS: api:50051
#      MICRO_REGISTRY: consul
#      MICRO_REGISTRY_ADDRESS: consul:8500
#      MICRO_SERVER_ADDRESS: :50051
#    links:
#      - taskmgr
#      - consul
#
#  api-taskmgr-client:
#    image: app-dccn-api-taskmgr-client
#    container_name: app-dccn-api-taskmgr-client
#    build:
#      context: .
#      dockerfile: ./dockerfile/api_task_client.Dockerfile
#    environment:
#      MICRO_REGISTRY: consul
#      MICRO_REGISTRY_ADDRESS: consul:8500
#      API_ADDRESS: "app-dccn-api:50051"
#    links:
#      - api
#      - taskmgr
#      - consul
