// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: account.proto

/*
Package usermgr is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	Request
	Name
	User
	Response
	Token
	Error
*/
package usermgr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserMgr service

type UserMgrService interface {
	// New Create a new user
	New(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// Gets the specified user
	Get(ctx context.Context, in *Name, opts ...client.CallOption) (*Response, error)
	// Auth  validates user
	NewToken(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error)
	// ValidateToken Validated Token
	VerifyToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error)
}

type userMgrService struct {
	c    client.Client
	name string
}

func NewUserMgrService(name string, c client.Client) UserMgrService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "usermgr"
	}
	return &userMgrService{
		c:    c,
		name: name,
	}
}

func (c *userMgrService) New(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "UserMgr.New", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMgrService) Get(ctx context.Context, in *Name, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "UserMgr.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMgrService) NewToken(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "UserMgr.NewToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMgrService) VerifyToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "UserMgr.VerifyToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserMgr service

type UserMgrHandler interface {
	// New Create a new user
	New(context.Context, *User, *Response) error
	// Gets the specified user
	Get(context.Context, *Name, *Response) error
	// Auth  validates user
	NewToken(context.Context, *User, *Token) error
	// ValidateToken Validated Token
	VerifyToken(context.Context, *Token, *Token) error
}

func RegisterUserMgrHandler(s server.Server, hdlr UserMgrHandler, opts ...server.HandlerOption) error {
	type userMgr interface {
		New(ctx context.Context, in *User, out *Response) error
		Get(ctx context.Context, in *Name, out *Response) error
		NewToken(ctx context.Context, in *User, out *Token) error
		VerifyToken(ctx context.Context, in *Token, out *Token) error
	}
	type UserMgr struct {
		userMgr
	}
	h := &userMgrHandler{hdlr}
	return s.Handle(s.NewHandler(&UserMgr{h}, opts...))
}

type userMgrHandler struct {
	UserMgrHandler
}

func (h *userMgrHandler) New(ctx context.Context, in *User, out *Response) error {
	return h.UserMgrHandler.New(ctx, in, out)
}

func (h *userMgrHandler) Get(ctx context.Context, in *Name, out *Response) error {
	return h.UserMgrHandler.Get(ctx, in, out)
}

func (h *userMgrHandler) NewToken(ctx context.Context, in *User, out *Token) error {
	return h.UserMgrHandler.NewToken(ctx, in, out)
}

func (h *userMgrHandler) VerifyToken(ctx context.Context, in *Token, out *Token) error {
	return h.UserMgrHandler.VerifyToken(ctx, in, out)
}
