// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package usermgr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	// id self-increase
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name should be unique
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// nickname show on UI
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// email user's email
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// password string
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	// balance user's balance in account
	Balance int32 `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	// is_deleted user's status
	IsDeleted            bool     `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *User) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Token struct {
	TokenString          string   `protobuf:"bytes,1,opt,name=token_string,json=tokenString,proto3" json:"token_string,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetTokenString() string {
	if m != nil {
		return m.TokenString
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "usermgr.Request")
	proto.RegisterType((*Name)(nil), "usermgr.Name")
	proto.RegisterType((*User)(nil), "usermgr.User")
	proto.RegisterType((*Response)(nil), "usermgr.Response")
	proto.RegisterType((*Token)(nil), "usermgr.Token")
	proto.RegisterType((*Error)(nil), "usermgr.Error")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x56, 0xd2, 0xa4, 0xc9, 0x4e, 0xe8, 0x22, 0xac, 0x95, 0x88, 0x22, 0x2a, 0x6d, 0x2d, 0x0e,
	0xab, 0x1e, 0x76, 0xa5, 0xe5, 0x56, 0xa9, 0x37, 0x2a, 0x2e, 0xb0, 0x07, 0x17, 0xb8, 0x56, 0x6e,
	0x32, 0x8d, 0xac, 0x66, 0xed, 0x60, 0x7b, 0xbb, 0xe2, 0xca, 0x2b, 0x70, 0xe5, 0x25, 0x78, 0x16,
	0x5e, 0x81, 0x07, 0x41, 0xb6, 0xf7, 0x8f, 0x22, 0xa1, 0xde, 0xfc, 0x7d, 0x33, 0xdf, 0xe7, 0x99,
	0xcf, 0x86, 0x13, 0x5e, 0xd7, 0x6a, 0x25, 0xed, 0xb4, 0xd7, 0xca, 0x2a, 0x92, 0xad, 0x0c, 0xea,
	0x65, 0xab, 0xab, 0x57, 0xad, 0x52, 0x6d, 0x87, 0x33, 0xde, 0x8b, 0x19, 0x97, 0x52, 0x59, 0x6e,
	0x85, 0x92, 0x26, 0xb4, 0xd1, 0x01, 0x64, 0x0c, 0xbf, 0xac, 0xd0, 0x58, 0x5a, 0x41, 0xb2, 0xe0,
	0x4b, 0x24, 0x04, 0x12, 0xc9, 0x97, 0x58, 0x46, 0xe3, 0x68, 0x32, 0x60, 0xfe, 0x4c, 0x7f, 0x46,
	0x90, 0x7c, 0x32, 0xa8, 0xc9, 0x10, 0x62, 0xd1, 0xf8, 0x52, 0xc2, 0x62, 0xd1, 0xec, 0x9a, 0xe3,
	0x7d, 0x33, 0xa9, 0x20, 0x97, 0xa2, 0xbe, 0xf7, 0x7c, 0xe2, 0xf9, 0x1d, 0x26, 0x23, 0x48, 0x71,
	0xc9, 0x45, 0x57, 0xa6, 0xbe, 0x10, 0x80, 0x53, 0xf4, 0xdc, 0x98, 0xb5, 0xd2, 0x4d, 0x79, 0x1c,
	0x14, 0x5b, 0x4c, 0x4a, 0xc8, 0x6e, 0x79, 0xc7, 0x65, 0x8d, 0x65, 0x36, 0x8e, 0x26, 0x29, 0xdb,
	0x42, 0x72, 0x0a, 0x20, 0xcc, 0x4d, 0x83, 0x1d, 0x5a, 0x6c, 0xca, 0x7c, 0x1c, 0x4d, 0x72, 0x36,
	0x10, 0xe6, 0x6d, 0x20, 0xe8, 0x35, 0xe4, 0x0c, 0x4d, 0xaf, 0xa4, 0x41, 0x72, 0x06, 0x89, 0xcb,
	0xc3, 0x0f, 0x5e, 0xcc, 0x4f, 0xa6, 0x9b, 0x70, 0xa6, 0x6e, 0x27, 0xe6, 0x4b, 0xe4, 0x35, 0xa4,
	0xa8, 0xb5, 0xd2, 0x7e, 0x95, 0x62, 0x3e, 0xdc, 0xf5, 0x5c, 0x39, 0x96, 0x85, 0x22, 0xbd, 0x83,
	0xf4, 0xa3, 0xba, 0x47, 0x49, 0xce, 0xe0, 0x99, 0x75, 0x87, 0x1b, 0x63, 0xb5, 0x90, 0xed, 0x26,
	0xad, 0xc2, 0x73, 0xd7, 0x9e, 0x72, 0xbb, 0x3e, 0xf0, 0x4e, 0x34, 0xde, 0x31, 0x67, 0x01, 0xec,
	0xef, 0x39, 0xfa, 0xdf, 0x3d, 0x97, 0x90, 0x7a, 0xec, 0x02, 0xae, 0x55, 0x13, 0x5e, 0x23, 0x65,
	0xfe, 0x4c, 0xc6, 0x50, 0x34, 0x68, 0x6a, 0x2d, 0x7a, 0xf7, 0x94, 0x9b, 0xec, 0x0f, 0xa9, 0xf9,
	0x8f, 0x18, 0x32, 0xb7, 0xdb, 0x87, 0x56, 0x93, 0x4b, 0x38, 0x5a, 0xe0, 0x9a, 0xfc, 0xbd, 0x74,
	0xf5, 0x62, 0x07, 0xb7, 0x21, 0xd1, 0xd1, 0xb7, 0x5f, 0xbf, 0xbf, 0xc7, 0x43, 0x3a, 0x98, 0xb9,
	0xd2, 0x4c, 0xe2, 0xfa, 0x22, 0x3a, 0x77, 0xf2, 0x77, 0x68, 0x0f, 0xe4, 0xee, 0x93, 0x3c, 0x41,
	0xde, 0xa2, 0x75, 0xf2, 0x2b, 0xc8, 0x17, 0xb8, 0x0e, 0x99, 0x3d, 0x1a, 0x61, 0xbf, 0xba, 0x2f,
	0xd3, 0xca, 0x1b, 0x8c, 0xe8, 0xf3, 0x60, 0xe0, 0xa3, 0xdc, 0x4e, 0xf1, 0x1e, 0x8a, 0xcf, 0xa8,
	0xc5, 0xdd, 0xd7, 0xe0, 0xf4, 0x48, 0xfa, 0x8f, 0xd5, 0xa9, 0xb7, 0x7a, 0x49, 0xc9, 0xa1, 0xd5,
	0x83, 0x37, 0xb8, 0x88, 0xce, 0x6f, 0x8f, 0xfd, 0xe7, 0x7f, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x3f, 0x3c, 0x8f, 0x00, 0x34, 0x03, 0x00, 0x00,
}
