// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dccenter/dccenter.proto

package dccenter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_725cbe6e0ead94da, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

// DataCenterList request message
type DataCenterListRequest struct {
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataCenterListRequest) Reset()         { *m = DataCenterListRequest{} }
func (m *DataCenterListRequest) String() string { return proto.CompactTextString(m) }
func (*DataCenterListRequest) ProtoMessage()    {}
func (*DataCenterListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_725cbe6e0ead94da, []int{1}
}

func (m *DataCenterListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListRequest.Unmarshal(m, b)
}
func (m *DataCenterListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListRequest.Marshal(b, m, deterministic)
}
func (m *DataCenterListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListRequest.Merge(m, src)
}
func (m *DataCenterListRequest) XXX_Size() int {
	return xxx_messageInfo_DataCenterListRequest.Size(m)
}
func (m *DataCenterListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListRequest proto.InternalMessageInfo

func (m *DataCenterListRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

type DataCenterInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataCenterInfo) Reset()         { *m = DataCenterInfo{} }
func (m *DataCenterInfo) String() string { return proto.CompactTextString(m) }
func (*DataCenterInfo) ProtoMessage()    {}
func (*DataCenterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_725cbe6e0ead94da, []int{2}
}

func (m *DataCenterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterInfo.Unmarshal(m, b)
}
func (m *DataCenterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterInfo.Marshal(b, m, deterministic)
}
func (m *DataCenterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterInfo.Merge(m, src)
}
func (m *DataCenterInfo) XXX_Size() int {
	return xxx_messageInfo_DataCenterInfo.Size(m)
}
func (m *DataCenterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterInfo proto.InternalMessageInfo

func (m *DataCenterInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataCenterInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DataCenterListResponse struct {
	DcList               []*DataCenterInfo `protobuf:"bytes,1,rep,name=dcList,proto3" json:"dcList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataCenterListResponse) Reset()         { *m = DataCenterListResponse{} }
func (m *DataCenterListResponse) String() string { return proto.CompactTextString(m) }
func (*DataCenterListResponse) ProtoMessage()    {}
func (*DataCenterListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_725cbe6e0ead94da, []int{3}
}

func (m *DataCenterListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListResponse.Unmarshal(m, b)
}
func (m *DataCenterListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListResponse.Marshal(b, m, deterministic)
}
func (m *DataCenterListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListResponse.Merge(m, src)
}
func (m *DataCenterListResponse) XXX_Size() int {
	return xxx_messageInfo_DataCenterListResponse.Size(m)
}
func (m *DataCenterListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListResponse proto.InternalMessageInfo

func (m *DataCenterListResponse) GetDcList() []*DataCenterInfo {
	if m != nil {
		return m.DcList
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "dccenter.Event")
	proto.RegisterType((*DataCenterListRequest)(nil), "dccenter.DataCenterListRequest")
	proto.RegisterType((*DataCenterInfo)(nil), "dccenter.DataCenterInfo")
	proto.RegisterType((*DataCenterListResponse)(nil), "dccenter.DataCenterListResponse")
}

func init() { proto.RegisterFile("proto/dccenter/dccenter.proto", fileDescriptor_725cbe6e0ead94da) }

var fileDescriptor_725cbe6e0ead94da = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x49, 0x4e, 0x4e, 0xcd, 0x2b, 0x49, 0x2d, 0x82, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0x1c, 0x30, 0xbe, 0x94, 0x4c, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x7e, 0x62, 0x41, 0xa6, 0x7e,
	0x62, 0x5e, 0x5e, 0x7e, 0x49, 0x62, 0x49, 0x66, 0x7e, 0x5e, 0x31, 0x44, 0x9d, 0x12, 0x3b, 0x17,
	0xab, 0x6b, 0x59, 0x6a, 0x5e, 0x89, 0x92, 0x29, 0x97, 0xa8, 0x4b, 0x62, 0x49, 0xa2, 0x33, 0x58,
	0x93, 0x4f, 0x66, 0x71, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x0c, 0x17, 0x67,
	0x69, 0x71, 0x6a, 0x51, 0x49, 0x7e, 0x76, 0x6a, 0x9e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x42, 0x40, 0xc9, 0x84, 0x8b, 0x0f, 0xa1, 0xcd, 0x33, 0x2f, 0x2d, 0x5f, 0x88, 0x8f, 0x8b, 0x29,
	0x33, 0x05, 0xac, 0x90, 0x39, 0x88, 0x29, 0x33, 0x45, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37,
	0x55, 0x82, 0x09, 0xac, 0x15, 0xcc, 0x56, 0xf2, 0xe2, 0x12, 0x43, 0xb7, 0xac, 0xb8, 0x20, 0x3f,
	0xaf, 0x38, 0x55, 0xc8, 0x80, 0x8b, 0x2d, 0x25, 0x19, 0x24, 0x22, 0xc1, 0xa8, 0xc0, 0xac, 0xc1,
	0x6d, 0x24, 0xa1, 0x07, 0xf7, 0x18, 0xaa, 0x3d, 0x41, 0x50, 0x75, 0x46, 0x55, 0x5c, 0x1c, 0x2e,
	0x50, 0x25, 0x42, 0x79, 0xc8, 0xae, 0x01, 0xc9, 0x0a, 0xc9, 0x63, 0xd3, 0x8f, 0xe4, 0x3d, 0x29,
	0x05, 0xdc, 0x0a, 0x20, 0x4e, 0x52, 0x92, 0x6c, 0xba, 0xfc, 0x64, 0x32, 0x93, 0xb0, 0x12, 0x1f,
	0x22, 0xb0, 0x73, 0x32, 0x8b, 0x4b, 0xac, 0x18, 0xb5, 0x92, 0xd8, 0xc0, 0x81, 0x68, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xdf, 0xcb, 0xeb, 0x05, 0x8d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DccenterClient is the client API for Dccenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DccenterClient interface {
	DataCenterList(ctx context.Context, in *DataCenterListRequest, opts ...grpc.CallOption) (*DataCenterListResponse, error)
}

type dccenterClient struct {
	cc *grpc.ClientConn
}

func NewDccenterClient(cc *grpc.ClientConn) DccenterClient {
	return &dccenterClient{cc}
}

func (c *dccenterClient) DataCenterList(ctx context.Context, in *DataCenterListRequest, opts ...grpc.CallOption) (*DataCenterListResponse, error) {
	out := new(DataCenterListResponse)
	err := c.cc.Invoke(ctx, "/dccenter.Dccenter/DataCenterList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DccenterServer is the server API for Dccenter service.
type DccenterServer interface {
	DataCenterList(context.Context, *DataCenterListRequest) (*DataCenterListResponse, error)
}

func RegisterDccenterServer(s *grpc.Server, srv DccenterServer) {
	s.RegisterService(&_Dccenter_serviceDesc, srv)
}

func _Dccenter_DataCenterList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataCenterListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DccenterServer).DataCenterList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dccenter.Dccenter/DataCenterList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DccenterServer).DataCenterList(ctx, req.(*DataCenterListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dccenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dccenter.Dccenter",
	HandlerType: (*DccenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataCenterList",
			Handler:    _Dccenter_DataCenterList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dccenter/dccenter.proto",
}
