// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/taskmgr/taskmgr.proto

package taskmgr

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpCode int32

const (
	OpCode_ADD    OpCode = 0
	OpCode_CANCEL OpCode = 1
	OpCode_UPDATE OpCode = 2
	OpCode_LIST   OpCode = 3
	OpCode_DETAIL OpCode = 4
)

var OpCode_name = map[int32]string{
	0: "ADD",
	1: "CANCEL",
	2: "UPDATE",
	3: "LIST",
	4: "DETAIL",
}

var OpCode_value = map[string]int32{
	"ADD":    0,
	"CANCEL": 1,
	"UPDATE": 2,
	"LIST":   3,
	"DETAIL": 4,
}

func (x OpCode) String() string {
	return proto.EnumName(OpCode_name, int32(x))
}

func (OpCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{0}
}

//Pub/Sub Event
type Event struct {
	// unique id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// unix timestamp
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Operation code
	Op                   OpCode   `protobuf:"varint,4,opt,name=op,proto3,enum=taskmgr.OpCode" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Event) GetOp() OpCode {
	if m != nil {
		return m.Op
	}
	return OpCode_ADD
}

type Task struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{1}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

// The dccn client request message containing the taskmgr's token
type AddTaskRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Datacenter           string   `protobuf:"bytes,3,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Usertoken            string   `protobuf:"bytes,4,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	Replica              int64    `protobuf:"varint,5,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskRequest) Reset()         { *m = AddTaskRequest{} }
func (m *AddTaskRequest) String() string { return proto.CompactTextString(m) }
func (*AddTaskRequest) ProtoMessage()    {}
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{2}
}

func (m *AddTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskRequest.Unmarshal(m, b)
}
func (m *AddTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskRequest.Marshal(b, m, deterministic)
}
func (m *AddTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskRequest.Merge(m, src)
}
func (m *AddTaskRequest) XXX_Size() int {
	return xxx_messageInfo_AddTaskRequest.Size(m)
}
func (m *AddTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskRequest proto.InternalMessageInfo

func (m *AddTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddTaskRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddTaskRequest) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *AddTaskRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

func (m *AddTaskRequest) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

// The Ankr Hub response message containing the success or failure
type AddTaskResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Taskid               int64    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskResponse) Reset()         { *m = AddTaskResponse{} }
func (m *AddTaskResponse) String() string { return proto.CompactTextString(m) }
func (*AddTaskResponse) ProtoMessage()    {}
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{3}
}

func (m *AddTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskResponse.Unmarshal(m, b)
}
func (m *AddTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskResponse.Marshal(b, m, deterministic)
}
func (m *AddTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskResponse.Merge(m, src)
}
func (m *AddTaskResponse) XXX_Size() int {
	return xxx_messageInfo_AddTaskResponse.Size(m)
}
func (m *AddTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskResponse proto.InternalMessageInfo

func (m *AddTaskResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AddTaskResponse) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

// The Client List request message
type TaskListRequest struct {
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskListRequest) Reset()         { *m = TaskListRequest{} }
func (m *TaskListRequest) String() string { return proto.CompactTextString(m) }
func (*TaskListRequest) ProtoMessage()    {}
func (*TaskListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{4}
}

func (m *TaskListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskListRequest.Unmarshal(m, b)
}
func (m *TaskListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskListRequest.Marshal(b, m, deterministic)
}
func (m *TaskListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListRequest.Merge(m, src)
}
func (m *TaskListRequest) XXX_Size() int {
	return xxx_messageInfo_TaskListRequest.Size(m)
}
func (m *TaskListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListRequest proto.InternalMessageInfo

func (m *TaskListRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

type TaskInfo struct {
	Taskid               int64    `protobuf:"varint,1,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Taskname             string   `protobuf:"bytes,2,opt,name=taskname,proto3" json:"taskname,omitempty"`
	Uptime               uint32   `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Creationdate         uint64   `protobuf:"varint,4,opt,name=creationdate,proto3" json:"creationdate,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Datacenter           string   `protobuf:"bytes,6,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Replica              int64    `protobuf:"varint,7,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskInfo) Reset()         { *m = TaskInfo{} }
func (m *TaskInfo) String() string { return proto.CompactTextString(m) }
func (*TaskInfo) ProtoMessage()    {}
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{5}
}

func (m *TaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskInfo.Unmarshal(m, b)
}
func (m *TaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskInfo.Marshal(b, m, deterministic)
}
func (m *TaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskInfo.Merge(m, src)
}
func (m *TaskInfo) XXX_Size() int {
	return xxx_messageInfo_TaskInfo.Size(m)
}
func (m *TaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TaskInfo proto.InternalMessageInfo

func (m *TaskInfo) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *TaskInfo) GetTaskname() string {
	if m != nil {
		return m.Taskname
	}
	return ""
}

func (m *TaskInfo) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *TaskInfo) GetCreationdate() uint64 {
	if m != nil {
		return m.Creationdate
	}
	return 0
}

func (m *TaskInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TaskInfo) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *TaskInfo) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

type TaskListResponse struct {
	Tasksinfo            []*TaskInfo `protobuf:"bytes,1,rep,name=tasksinfo,proto3" json:"tasksinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TaskListResponse) Reset()         { *m = TaskListResponse{} }
func (m *TaskListResponse) String() string { return proto.CompactTextString(m) }
func (*TaskListResponse) ProtoMessage()    {}
func (*TaskListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{6}
}

func (m *TaskListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskListResponse.Unmarshal(m, b)
}
func (m *TaskListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskListResponse.Marshal(b, m, deterministic)
}
func (m *TaskListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListResponse.Merge(m, src)
}
func (m *TaskListResponse) XXX_Size() int {
	return xxx_messageInfo_TaskListResponse.Size(m)
}
func (m *TaskListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListResponse proto.InternalMessageInfo

func (m *TaskListResponse) GetTasksinfo() []*TaskInfo {
	if m != nil {
		return m.Tasksinfo
	}
	return nil
}

type CancelTaskRequest struct {
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	Taskid               int64    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTaskRequest) Reset()         { *m = CancelTaskRequest{} }
func (m *CancelTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CancelTaskRequest) ProtoMessage()    {}
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{7}
}

func (m *CancelTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTaskRequest.Unmarshal(m, b)
}
func (m *CancelTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTaskRequest.Marshal(b, m, deterministic)
}
func (m *CancelTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTaskRequest.Merge(m, src)
}
func (m *CancelTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CancelTaskRequest.Size(m)
}
func (m *CancelTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTaskRequest proto.InternalMessageInfo

func (m *CancelTaskRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

func (m *CancelTaskRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

type CancelTaskResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTaskResponse) Reset()         { *m = CancelTaskResponse{} }
func (m *CancelTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CancelTaskResponse) ProtoMessage()    {}
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{8}
}

func (m *CancelTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTaskResponse.Unmarshal(m, b)
}
func (m *CancelTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTaskResponse.Marshal(b, m, deterministic)
}
func (m *CancelTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTaskResponse.Merge(m, src)
}
func (m *CancelTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CancelTaskResponse.Size(m)
}
func (m *CancelTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTaskResponse proto.InternalMessageInfo

func (m *CancelTaskResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpdateTaskRequest struct {
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	Taskid               int64    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Replica              int64    `protobuf:"varint,4,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{9}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

func (m *UpdateTaskRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *UpdateTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateTaskRequest) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

type UpdateTaskResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskResponse) Reset()         { *m = UpdateTaskResponse{} }
func (m *UpdateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskResponse) ProtoMessage()    {}
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{10}
}

func (m *UpdateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskResponse.Unmarshal(m, b)
}
func (m *UpdateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskResponse.Merge(m, src)
}
func (m *UpdateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskResponse.Size(m)
}
func (m *UpdateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskResponse proto.InternalMessageInfo

func (m *UpdateTaskResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type TaskDetailRequest struct {
	Taskid               int64    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskDetailRequest) Reset()         { *m = TaskDetailRequest{} }
func (m *TaskDetailRequest) String() string { return proto.CompactTextString(m) }
func (*TaskDetailRequest) ProtoMessage()    {}
func (*TaskDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{11}
}

func (m *TaskDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetailRequest.Unmarshal(m, b)
}
func (m *TaskDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetailRequest.Marshal(b, m, deterministic)
}
func (m *TaskDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetailRequest.Merge(m, src)
}
func (m *TaskDetailRequest) XXX_Size() int {
	return xxx_messageInfo_TaskDetailRequest.Size(m)
}
func (m *TaskDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetailRequest proto.InternalMessageInfo

func (m *TaskDetailRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *TaskDetailRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

type TaskDetailResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskDetailResponse) Reset()         { *m = TaskDetailResponse{} }
func (m *TaskDetailResponse) String() string { return proto.CompactTextString(m) }
func (*TaskDetailResponse) ProtoMessage()    {}
func (*TaskDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_767369fe375565d7, []int{12}
}

func (m *TaskDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetailResponse.Unmarshal(m, b)
}
func (m *TaskDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetailResponse.Marshal(b, m, deterministic)
}
func (m *TaskDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetailResponse.Merge(m, src)
}
func (m *TaskDetailResponse) XXX_Size() int {
	return xxx_messageInfo_TaskDetailResponse.Size(m)
}
func (m *TaskDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetailResponse proto.InternalMessageInfo

func (m *TaskDetailResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterEnum("taskmgr.OpCode", OpCode_name, OpCode_value)
	proto.RegisterType((*Event)(nil), "taskmgr.Event")
	proto.RegisterType((*Task)(nil), "taskmgr.Task")
	proto.RegisterType((*AddTaskRequest)(nil), "taskmgr.AddTaskRequest")
	proto.RegisterType((*AddTaskResponse)(nil), "taskmgr.AddTaskResponse")
	proto.RegisterType((*TaskListRequest)(nil), "taskmgr.TaskListRequest")
	proto.RegisterType((*TaskInfo)(nil), "taskmgr.TaskInfo")
	proto.RegisterType((*TaskListResponse)(nil), "taskmgr.TaskListResponse")
	proto.RegisterType((*CancelTaskRequest)(nil), "taskmgr.CancelTaskRequest")
	proto.RegisterType((*CancelTaskResponse)(nil), "taskmgr.CancelTaskResponse")
	proto.RegisterType((*UpdateTaskRequest)(nil), "taskmgr.UpdateTaskRequest")
	proto.RegisterType((*UpdateTaskResponse)(nil), "taskmgr.UpdateTaskResponse")
	proto.RegisterType((*TaskDetailRequest)(nil), "taskmgr.TaskDetailRequest")
	proto.RegisterType((*TaskDetailResponse)(nil), "taskmgr.TaskDetailResponse")
}

func init() { proto.RegisterFile("proto/taskmgr/taskmgr.proto", fileDescriptor_767369fe375565d7) }

var fileDescriptor_767369fe375565d7 = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcf, 0x6e, 0x1a, 0x3f,
	0x10, 0xfe, 0xed, 0x9f, 0x40, 0x98, 0x5f, 0x12, 0xc0, 0xaa, 0x9a, 0xed, 0x26, 0x6a, 0x91, 0x4f,
	0x28, 0x8a, 0x82, 0x94, 0xde, 0x72, 0xa9, 0x10, 0x70, 0x40, 0xa2, 0x7f, 0xb4, 0x25, 0x87, 0x1e,
	0x1d, 0xd6, 0x41, 0xab, 0xc0, 0xda, 0x5d, 0x9b, 0x56, 0xb9, 0xf6, 0x09, 0x2a, 0xf5, 0xb5, 0x7a,
	0xeb, 0x2b, 0xe4, 0x41, 0x2a, 0x1b, 0xef, 0xae, 0xb7, 0x4b, 0xd2, 0x43, 0x4f, 0xcc, 0xcc, 0x8e,
	0xbf, 0xf9, 0xe6, 0x9b, 0xb1, 0x81, 0x13, 0x9e, 0x31, 0xc9, 0x06, 0x92, 0x88, 0xbb, 0xf5, 0x32,
	0xcb, 0x7f, 0x2f, 0x74, 0x14, 0x35, 0x8d, 0x1b, 0x9e, 0x2e, 0x19, 0x5b, 0xae, 0xe8, 0x80, 0xf0,
	0x64, 0x40, 0xd2, 0x94, 0x49, 0x22, 0x13, 0x96, 0x8a, 0x6d, 0x1a, 0xe6, 0xb0, 0x37, 0xf9, 0x42,
	0x53, 0x89, 0x8e, 0xc0, 0x4d, 0xe2, 0xc0, 0xe9, 0x39, 0xfd, 0x56, 0xe4, 0x26, 0x31, 0x3a, 0x85,
	0x96, 0x4c, 0xd6, 0x54, 0x48, 0xb2, 0xe6, 0x81, 0xdb, 0x73, 0xfa, 0x5e, 0x54, 0x06, 0x50, 0x00,
	0xcd, 0x35, 0x15, 0x82, 0x2c, 0x69, 0xe0, 0xe9, 0x23, 0xb9, 0x8b, 0x5e, 0x81, 0xcb, 0x78, 0xe0,
	0xf7, 0x9c, 0xfe, 0xd1, 0x65, 0xfb, 0x22, 0xe7, 0xf4, 0x9e, 0x8f, 0x58, 0x4c, 0x23, 0x97, 0x71,
	0xdc, 0x00, 0x7f, 0x4e, 0xc4, 0x1d, 0xfe, 0xee, 0xc0, 0xd1, 0x30, 0x8e, 0x95, 0x1d, 0xd1, 0xcf,
	0x1b, 0x2a, 0x24, 0x42, 0xe0, 0xa7, 0x64, 0x4d, 0x0d, 0x0b, 0x6d, 0xab, 0x98, 0xbc, 0xe7, 0x54,
	0x53, 0x68, 0x45, 0xda, 0x46, 0x2f, 0x01, 0x62, 0x22, 0xc9, 0x82, 0xa6, 0x92, 0x66, 0x86, 0x80,
	0x15, 0x51, 0xdc, 0x37, 0x82, 0x66, 0x92, 0xdd, 0xd1, 0x54, 0x53, 0x69, 0x45, 0x65, 0x40, 0x71,
	0xcf, 0x28, 0x5f, 0x25, 0x0b, 0x12, 0xec, 0xe9, 0xbe, 0x72, 0x17, 0x0f, 0xa1, 0x5d, 0x30, 0x12,
	0x9c, 0xa5, 0x82, 0xa2, 0xe7, 0xd0, 0x10, 0x92, 0xc8, 0x8d, 0x30, 0xa4, 0x8c, 0xa7, 0xe2, 0xaa,
	0xb7, 0x24, 0x36, 0xda, 0x18, 0x0f, 0x0f, 0xa0, 0xad, 0xce, 0xcf, 0x12, 0x21, 0xf3, 0xae, 0x2a,
	0x6c, 0x9c, 0x3f, 0xd8, 0xe0, 0x9f, 0x0e, 0xec, 0xab, 0x13, 0xd3, 0xf4, 0x96, 0x59, 0xa8, 0x8e,
	0x8d, 0x8a, 0x42, 0xd8, 0x57, 0x96, 0x16, 0x67, 0x2b, 0x44, 0xe1, 0xab, 0x33, 0x1b, 0xae, 0x26,
	0xa3, 0x85, 0x38, 0x8c, 0x8c, 0x87, 0x30, 0x1c, 0x2c, 0x32, 0xaa, 0x87, 0x1d, 0x13, 0x49, 0xb5,
	0x0e, 0x7e, 0x54, 0x89, 0x59, 0xdd, 0xed, 0x55, 0xba, 0xab, 0x0a, 0xdc, 0xa8, 0x09, 0x6c, 0x49,
	0xd8, 0xac, 0x4a, 0x38, 0x82, 0x4e, 0xd9, 0xbf, 0xd1, 0x70, 0x00, 0x2d, 0xc5, 0x56, 0x24, 0xe9,
	0x2d, 0x0b, 0x9c, 0x9e, 0xd7, 0xff, 0xff, 0xb2, 0x5b, 0x6c, 0x46, 0xde, 0x7b, 0x54, 0xe6, 0xe0,
	0x29, 0x74, 0x47, 0x24, 0x5d, 0xd0, 0x95, 0xbd, 0x1c, 0x4f, 0xca, 0xf8, 0xe8, 0x3c, 0xce, 0x01,
	0xd9, 0x50, 0x4f, 0x4f, 0x15, 0x7f, 0x85, 0xee, 0x35, 0x57, 0xca, 0xfc, 0x73, 0xe1, 0x62, 0x97,
	0x3d, 0x6b, 0x97, 0x2d, 0xd9, 0xfc, 0xaa, 0x6c, 0xe7, 0x80, 0xec, 0xc2, 0x7f, 0xa1, 0x39, 0x85,
	0xae, 0xca, 0x1b, 0x53, 0x49, 0x92, 0x55, 0x4e, 0xf3, 0x31, 0x22, 0x4f, 0xaf, 0x5f, 0x1f, 0x90,
	0x0d, 0x65, 0x0a, 0x23, 0xf0, 0x6f, 0x58, 0x7c, 0x9f, 0x5f, 0x44, 0x65, 0x9f, 0xbd, 0x81, 0xc6,
	0xf6, 0x16, 0xa3, 0x26, 0x78, 0xc3, 0xf1, 0xb8, 0xf3, 0x1f, 0x02, 0x68, 0x8c, 0x86, 0xef, 0x46,
	0x93, 0x59, 0xc7, 0x51, 0xf6, 0xf5, 0x87, 0xf1, 0x70, 0x3e, 0xe9, 0xb8, 0x68, 0x1f, 0xfc, 0xd9,
	0xf4, 0xe3, 0xbc, 0xe3, 0xa9, 0xe8, 0x78, 0x32, 0x1f, 0x4e, 0x67, 0x1d, 0xff, 0xf2, 0xc1, 0x83,
	0xa6, 0xaa, 0xf5, 0x76, 0x99, 0xa1, 0x6b, 0x68, 0x9a, 0x9b, 0x86, 0x8e, 0x8b, 0x55, 0xa8, 0xbe,
	0x06, 0x61, 0x50, 0xff, 0xb0, 0xa5, 0x87, 0x8f, 0xbf, 0xfd, 0x7a, 0xf8, 0xe1, 0x76, 0xf1, 0x41,
	0xf1, 0xf6, 0x91, 0x38, 0xbe, 0x72, 0xce, 0x10, 0x01, 0x28, 0xa7, 0x8d, 0xc2, 0x02, 0xa0, 0xb6,
	0x4d, 0xe1, 0xc9, 0xce, 0x6f, 0x06, 0x3f, 0xd4, 0xf8, 0xcf, 0x70, 0xbb, 0xc0, 0x5f, 0xe8, 0x24,
	0x53, 0xa2, 0x9c, 0x94, 0x55, 0xa2, 0xb6, 0x37, 0x56, 0x89, 0xfa, 0x68, 0x77, 0x94, 0xd8, 0xe8,
	0x24, 0x55, 0xe2, 0xd3, 0xf6, 0x45, 0x50, 0x77, 0x08, 0x05, 0x95, 0x8b, 0x62, 0x3d, 0x2b, 0xe1,
	0x8b, 0x1d, 0x5f, 0x0c, 0x78, 0xa0, 0xc1, 0x11, 0x3e, 0x2c, 0xc0, 0x57, 0x89, 0x90, 0x86, 0x7d,
	0x39, 0x6e, 0x8b, 0x7d, 0x6d, 0x9d, 0x2c, 0xf6, 0xf5, 0xfd, 0xd8, 0xc1, 0x3e, 0xd6, 0x09, 0x57,
	0xce, 0xd9, 0x4d, 0x43, 0xff, 0xb1, 0xbc, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x34, 0x05, 0x90,
	0x29, 0x9e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskMgrClient is the client API for TaskMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskMgrClient interface {
	AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error)
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
	TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error)
	TaskDetail(ctx context.Context, in *TaskDetailRequest, opts ...grpc.CallOption) (*TaskDetailResponse, error)
}

type taskMgrClient struct {
	cc *grpc.ClientConn
}

func NewTaskMgrClient(cc *grpc.ClientConn) TaskMgrClient {
	return &taskMgrClient{cc}
}

func (c *taskMgrClient) AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error) {
	out := new(AddTaskResponse)
	err := c.cc.Invoke(ctx, "/taskmgr.TaskMgr/AddTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMgrClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, "/taskmgr.TaskMgr/CancelTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMgrClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, "/taskmgr.TaskMgr/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMgrClient) TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error) {
	out := new(TaskListResponse)
	err := c.cc.Invoke(ctx, "/taskmgr.TaskMgr/TaskList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMgrClient) TaskDetail(ctx context.Context, in *TaskDetailRequest, opts ...grpc.CallOption) (*TaskDetailResponse, error) {
	out := new(TaskDetailResponse)
	err := c.cc.Invoke(ctx, "/taskmgr.TaskMgr/TaskDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskMgrServer is the server API for TaskMgr service.
type TaskMgrServer interface {
	AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error)
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	TaskList(context.Context, *TaskListRequest) (*TaskListResponse, error)
	TaskDetail(context.Context, *TaskDetailRequest) (*TaskDetailResponse, error)
}

func RegisterTaskMgrServer(s *grpc.Server, srv TaskMgrServer) {
	s.RegisterService(&_TaskMgr_serviceDesc, srv)
}

func _TaskMgr_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMgrServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskmgr.TaskMgr/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMgrServer).AddTask(ctx, req.(*AddTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMgr_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMgrServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskmgr.TaskMgr/CancelTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMgrServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMgr_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMgrServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskmgr.TaskMgr/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMgrServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMgr_TaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMgrServer).TaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskmgr.TaskMgr/TaskList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMgrServer).TaskList(ctx, req.(*TaskListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMgr_TaskDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMgrServer).TaskDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskmgr.TaskMgr/TaskDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMgrServer).TaskDetail(ctx, req.(*TaskDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taskmgr.TaskMgr",
	HandlerType: (*TaskMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _TaskMgr_AddTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _TaskMgr_CancelTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskMgr_UpdateTask_Handler,
		},
		{
			MethodName: "TaskList",
			Handler:    _TaskMgr_TaskList_Handler,
		},
		{
			MethodName: "TaskDetail",
			Handler:    _TaskMgr_TaskDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/taskmgr/taskmgr.proto",
}
