// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/taskmgr/taskmgr.proto

/*
Package go_micro_api_taskmgr is a generated protocol buffer package.

It is generated from these files:
	proto/taskmgr/taskmgr.proto

It has these top-level messages:
	ID
	Task
	Response
	Event
*/
package go_micro_api_taskmgr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TaskApi service

type TaskApiService interface {
	Get(ctx context.Context, in *ID, opts ...client.CallOption) (*Task, error)
	Create(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error)
	Cancel(ctx context.Context, in *ID, opts ...client.CallOption) (*Response, error)
	Update(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error)
}

type taskApiService struct {
	c    client.Client
	name string
}

func NewTaskApiService(name string, c client.Client) TaskApiService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.api.taskmgr"
	}
	return &taskApiService{
		c:    c,
		name: name,
	}
}

func (c *taskApiService) Get(ctx context.Context, in *ID, opts ...client.CallOption) (*Task, error) {
	req := c.c.NewRequest(c.name, "TaskApi.Get", in)
	out := new(Task)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskApiService) Create(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TaskApi.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskApiService) Cancel(ctx context.Context, in *ID, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TaskApi.Cancel", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskApiService) Update(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TaskApi.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskApi service

type TaskApiHandler interface {
	Get(context.Context, *ID, *Task) error
	Create(context.Context, *Task, *Response) error
	Cancel(context.Context, *ID, *Response) error
	Update(context.Context, *Task, *Response) error
}

func RegisterTaskApiHandler(s server.Server, hdlr TaskApiHandler, opts ...server.HandlerOption) error {
	type taskApi interface {
		Get(ctx context.Context, in *ID, out *Task) error
		Create(ctx context.Context, in *Task, out *Response) error
		Cancel(ctx context.Context, in *ID, out *Response) error
		Update(ctx context.Context, in *Task, out *Response) error
	}
	type TaskApi struct {
		taskApi
	}
	h := &taskApiHandler{hdlr}
	return s.Handle(s.NewHandler(&TaskApi{h}, opts...))
}

type taskApiHandler struct {
	TaskApiHandler
}

func (h *taskApiHandler) Get(ctx context.Context, in *ID, out *Task) error {
	return h.TaskApiHandler.Get(ctx, in, out)
}

func (h *taskApiHandler) Create(ctx context.Context, in *Task, out *Response) error {
	return h.TaskApiHandler.Create(ctx, in, out)
}

func (h *taskApiHandler) Cancel(ctx context.Context, in *ID, out *Response) error {
	return h.TaskApiHandler.Cancel(ctx, in, out)
}

func (h *taskApiHandler) Update(ctx context.Context, in *Task, out *Response) error {
	return h.TaskApiHandler.Update(ctx, in, out)
}
