// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/taskmgr.proto

package taskmgr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpCode int32

const (
	OpCode_ADD    OpCode = 0
	OpCode_CANCEL OpCode = 1
	OpCode_UPDATE OpCode = 2
	OpCode_LIST   OpCode = 3
	OpCode_DETAIL OpCode = 4
)

var OpCode_name = map[int32]string{
	0: "ADD",
	1: "CANCEL",
	2: "UPDATE",
	3: "LIST",
	4: "DETAIL",
}

var OpCode_value = map[string]int32{
	"ADD":    0,
	"CANCEL": 1,
	"UPDATE": 2,
	"LIST":   3,
	"DETAIL": 4,
}

func (x OpCode) String() string {
	return proto.EnumName(OpCode_name, int32(x))
}

func (OpCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{0}
}

//Pub/Sub Event
type Event struct {
	// unique id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// unix timestamp
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Operation code
	Op                   OpCode   `protobuf:"varint,4,opt,name=op,proto3,enum=taskmgr.OpCode" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Event) GetOp() OpCode {
	if m != nil {
		return m.Op
	}
	return OpCode_ADD
}

// The dccn client request message containing the user's token
type AddTaskRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Datacenter           string   `protobuf:"bytes,3,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Usertoken            string   `protobuf:"bytes,4,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	Replica              int64    `protobuf:"varint,5,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskRequest) Reset()         { *m = AddTaskRequest{} }
func (m *AddTaskRequest) String() string { return proto.CompactTextString(m) }
func (*AddTaskRequest) ProtoMessage()    {}
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{1}
}

func (m *AddTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskRequest.Unmarshal(m, b)
}
func (m *AddTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskRequest.Marshal(b, m, deterministic)
}
func (m *AddTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskRequest.Merge(m, src)
}
func (m *AddTaskRequest) XXX_Size() int {
	return xxx_messageInfo_AddTaskRequest.Size(m)
}
func (m *AddTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskRequest proto.InternalMessageInfo

func (m *AddTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddTaskRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddTaskRequest) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *AddTaskRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

func (m *AddTaskRequest) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

// The Ankr Hub response message containing the success or failure
type AddTaskResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Taskid               int64    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskResponse) Reset()         { *m = AddTaskResponse{} }
func (m *AddTaskResponse) String() string { return proto.CompactTextString(m) }
func (*AddTaskResponse) ProtoMessage()    {}
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{2}
}

func (m *AddTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskResponse.Unmarshal(m, b)
}
func (m *AddTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskResponse.Marshal(b, m, deterministic)
}
func (m *AddTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskResponse.Merge(m, src)
}
func (m *AddTaskResponse) XXX_Size() int {
	return xxx_messageInfo_AddTaskResponse.Size(m)
}
func (m *AddTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskResponse proto.InternalMessageInfo

func (m *AddTaskResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AddTaskResponse) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

// The Client List request message
type TaskListRequest struct {
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskListRequest) Reset()         { *m = TaskListRequest{} }
func (m *TaskListRequest) String() string { return proto.CompactTextString(m) }
func (*TaskListRequest) ProtoMessage()    {}
func (*TaskListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{3}
}

func (m *TaskListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskListRequest.Unmarshal(m, b)
}
func (m *TaskListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskListRequest.Marshal(b, m, deterministic)
}
func (m *TaskListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListRequest.Merge(m, src)
}
func (m *TaskListRequest) XXX_Size() int {
	return xxx_messageInfo_TaskListRequest.Size(m)
}
func (m *TaskListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListRequest proto.InternalMessageInfo

func (m *TaskListRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

type TaskInfo struct {
	Taskid               int64    `protobuf:"varint,1,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Taskname             string   `protobuf:"bytes,2,opt,name=taskname,proto3" json:"taskname,omitempty"`
	Uptime               uint32   `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Creationdate         uint64   `protobuf:"varint,4,opt,name=creationdate,proto3" json:"creationdate,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Datacenter           string   `protobuf:"bytes,6,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Replica              int64    `protobuf:"varint,7,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskInfo) Reset()         { *m = TaskInfo{} }
func (m *TaskInfo) String() string { return proto.CompactTextString(m) }
func (*TaskInfo) ProtoMessage()    {}
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{4}
}

func (m *TaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskInfo.Unmarshal(m, b)
}
func (m *TaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskInfo.Marshal(b, m, deterministic)
}
func (m *TaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskInfo.Merge(m, src)
}
func (m *TaskInfo) XXX_Size() int {
	return xxx_messageInfo_TaskInfo.Size(m)
}
func (m *TaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TaskInfo proto.InternalMessageInfo

func (m *TaskInfo) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *TaskInfo) GetTaskname() string {
	if m != nil {
		return m.Taskname
	}
	return ""
}

func (m *TaskInfo) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *TaskInfo) GetCreationdate() uint64 {
	if m != nil {
		return m.Creationdate
	}
	return 0
}

func (m *TaskInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TaskInfo) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *TaskInfo) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

type TaskListResponse struct {
	Tasksinfo            []*TaskInfo `protobuf:"bytes,1,rep,name=tasksinfo,proto3" json:"tasksinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TaskListResponse) Reset()         { *m = TaskListResponse{} }
func (m *TaskListResponse) String() string { return proto.CompactTextString(m) }
func (*TaskListResponse) ProtoMessage()    {}
func (*TaskListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{5}
}

func (m *TaskListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskListResponse.Unmarshal(m, b)
}
func (m *TaskListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskListResponse.Marshal(b, m, deterministic)
}
func (m *TaskListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListResponse.Merge(m, src)
}
func (m *TaskListResponse) XXX_Size() int {
	return xxx_messageInfo_TaskListResponse.Size(m)
}
func (m *TaskListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListResponse proto.InternalMessageInfo

func (m *TaskListResponse) GetTasksinfo() []*TaskInfo {
	if m != nil {
		return m.Tasksinfo
	}
	return nil
}

type CancelTaskRequest struct {
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	Taskid               int64    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTaskRequest) Reset()         { *m = CancelTaskRequest{} }
func (m *CancelTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CancelTaskRequest) ProtoMessage()    {}
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{6}
}

func (m *CancelTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTaskRequest.Unmarshal(m, b)
}
func (m *CancelTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTaskRequest.Marshal(b, m, deterministic)
}
func (m *CancelTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTaskRequest.Merge(m, src)
}
func (m *CancelTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CancelTaskRequest.Size(m)
}
func (m *CancelTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTaskRequest proto.InternalMessageInfo

func (m *CancelTaskRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

func (m *CancelTaskRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

type CancelTaskResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTaskResponse) Reset()         { *m = CancelTaskResponse{} }
func (m *CancelTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CancelTaskResponse) ProtoMessage()    {}
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{7}
}

func (m *CancelTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTaskResponse.Unmarshal(m, b)
}
func (m *CancelTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTaskResponse.Marshal(b, m, deterministic)
}
func (m *CancelTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTaskResponse.Merge(m, src)
}
func (m *CancelTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CancelTaskResponse.Size(m)
}
func (m *CancelTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTaskResponse proto.InternalMessageInfo

func (m *CancelTaskResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpdateTaskRequest struct {
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	Taskid               int64    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Replica              int64    `protobuf:"varint,4,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{8}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

func (m *UpdateTaskRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *UpdateTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateTaskRequest) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

type UpdateTaskResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskResponse) Reset()         { *m = UpdateTaskResponse{} }
func (m *UpdateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskResponse) ProtoMessage()    {}
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{9}
}

func (m *UpdateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskResponse.Unmarshal(m, b)
}
func (m *UpdateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskResponse.Merge(m, src)
}
func (m *UpdateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskResponse.Size(m)
}
func (m *UpdateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskResponse proto.InternalMessageInfo

func (m *UpdateTaskResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type TaskDetailRequest struct {
	Taskid               int64    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskDetailRequest) Reset()         { *m = TaskDetailRequest{} }
func (m *TaskDetailRequest) String() string { return proto.CompactTextString(m) }
func (*TaskDetailRequest) ProtoMessage()    {}
func (*TaskDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{10}
}

func (m *TaskDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetailRequest.Unmarshal(m, b)
}
func (m *TaskDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetailRequest.Marshal(b, m, deterministic)
}
func (m *TaskDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetailRequest.Merge(m, src)
}
func (m *TaskDetailRequest) XXX_Size() int {
	return xxx_messageInfo_TaskDetailRequest.Size(m)
}
func (m *TaskDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetailRequest proto.InternalMessageInfo

func (m *TaskDetailRequest) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *TaskDetailRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

type TaskDetailResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskDetailResponse) Reset()         { *m = TaskDetailResponse{} }
func (m *TaskDetailResponse) String() string { return proto.CompactTextString(m) }
func (*TaskDetailResponse) ProtoMessage()    {}
func (*TaskDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{11}
}

func (m *TaskDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetailResponse.Unmarshal(m, b)
}
func (m *TaskDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetailResponse.Marshal(b, m, deterministic)
}
func (m *TaskDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetailResponse.Merge(m, src)
}
func (m *TaskDetailResponse) XXX_Size() int {
	return xxx_messageInfo_TaskDetailResponse.Size(m)
}
func (m *TaskDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetailResponse proto.InternalMessageInfo

func (m *TaskDetailResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Task struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Taskid               int64    `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	TaskType             string   `protobuf:"bytes,3,opt,name=taskType,proto3" json:"taskType,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Replica              int64    `protobuf:"varint,6,opt,name=replica,proto3" json:"replica,omitempty"`
	Extra                string   `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{12}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Task) GetTaskid() int64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

func (m *Task) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Task) GetReplica() int64 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *Task) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type TaskResult struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               int64    `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResult) Reset()         { *m = TaskResult{} }
func (m *TaskResult) String() string { return proto.CompactTextString(m) }
func (*TaskResult) ProtoMessage()    {}
func (*TaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae8043a71c8a211, []int{13}
}

func (m *TaskResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResult.Unmarshal(m, b)
}
func (m *TaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResult.Marshal(b, m, deterministic)
}
func (m *TaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResult.Merge(m, src)
}
func (m *TaskResult) XXX_Size() int {
	return xxx_messageInfo_TaskResult.Size(m)
}
func (m *TaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResult proto.InternalMessageInfo

func (m *TaskResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskResult) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("taskmgr.OpCode", OpCode_name, OpCode_value)
	proto.RegisterType((*Event)(nil), "taskmgr.Event")
	proto.RegisterType((*AddTaskRequest)(nil), "taskmgr.AddTaskRequest")
	proto.RegisterType((*AddTaskResponse)(nil), "taskmgr.AddTaskResponse")
	proto.RegisterType((*TaskListRequest)(nil), "taskmgr.TaskListRequest")
	proto.RegisterType((*TaskInfo)(nil), "taskmgr.TaskInfo")
	proto.RegisterType((*TaskListResponse)(nil), "taskmgr.TaskListResponse")
	proto.RegisterType((*CancelTaskRequest)(nil), "taskmgr.CancelTaskRequest")
	proto.RegisterType((*CancelTaskResponse)(nil), "taskmgr.CancelTaskResponse")
	proto.RegisterType((*UpdateTaskRequest)(nil), "taskmgr.UpdateTaskRequest")
	proto.RegisterType((*UpdateTaskResponse)(nil), "taskmgr.UpdateTaskResponse")
	proto.RegisterType((*TaskDetailRequest)(nil), "taskmgr.TaskDetailRequest")
	proto.RegisterType((*TaskDetailResponse)(nil), "taskmgr.TaskDetailResponse")
	proto.RegisterType((*Task)(nil), "taskmgr.Task")
	proto.RegisterType((*TaskResult)(nil), "taskmgr.TaskResult")
}

func init() { proto.RegisterFile("proto/taskmgr.proto", fileDescriptor_fae8043a71c8a211) }

var fileDescriptor_fae8043a71c8a211 = []byte{
	// 746 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x27, 0x4d, 0xda, 0xae, 0x8f, 0x6d, 0x6d, 0xcd, 0xb4, 0x85, 0x30, 0x41, 0xe5, 0x53, 0x35,
	0x4d, 0xab, 0x34, 0x38, 0xed, 0x82, 0xaa, 0xb6, 0x87, 0x4a, 0xe5, 0x8f, 0x42, 0x77, 0xe0, 0xe8,
	0x35, 0x5e, 0x15, 0xad, 0x8d, 0x43, 0xec, 0x02, 0xbb, 0xf2, 0x09, 0x90, 0xf8, 0x12, 0x7c, 0x18,
	0x6e, 0x7c, 0x85, 0x7d, 0x10, 0x64, 0xc7, 0x49, 0x1c, 0xd2, 0x8d, 0x03, 0x37, 0x3f, 0xfb, 0xf9,
	0xfd, 0x7e, 0xef, 0x97, 0x9f, 0x5f, 0xe0, 0x49, 0x9c, 0x30, 0xc1, 0x06, 0x82, 0xf0, 0x9b, 0xf5,
	0x32, 0x39, 0x53, 0x11, 0x6a, 0xea, 0xd0, 0x3b, 0x5e, 0x32, 0xb6, 0x5c, 0xd1, 0x01, 0x89, 0xc3,
	0x01, 0x89, 0x22, 0x26, 0x88, 0x08, 0x59, 0xc4, 0xd3, 0x34, 0x1c, 0x43, 0x7d, 0xf2, 0x99, 0x46,
	0x02, 0xed, 0x43, 0x2d, 0x0c, 0x5c, 0xab, 0x67, 0xf5, 0x5b, 0x7e, 0x2d, 0x0c, 0xd0, 0x31, 0xb4,
	0x44, 0xb8, 0xa6, 0x5c, 0x90, 0x75, 0xec, 0xd6, 0x7a, 0x56, 0xdf, 0xf6, 0x8b, 0x0d, 0xe4, 0x42,
	0x73, 0x4d, 0x39, 0x27, 0x4b, 0xea, 0xda, 0xea, 0x4a, 0x16, 0xa2, 0x17, 0x50, 0x63, 0xb1, 0xeb,
	0xf4, 0xac, 0xfe, 0xfe, 0x79, 0xfb, 0x2c, 0xe3, 0xf4, 0x2e, 0x1e, 0xb1, 0x80, 0xfa, 0x35, 0x16,
	0xe3, 0xef, 0x16, 0xec, 0x0f, 0x83, 0x60, 0x4e, 0xf8, 0x8d, 0x4f, 0x3f, 0x6d, 0x28, 0x17, 0x08,
	0x81, 0x13, 0x91, 0x35, 0xd5, 0xe8, 0x6a, 0x2d, 0xf7, 0xc4, 0x6d, 0x4c, 0x15, 0x74, 0xcb, 0x57,
	0x6b, 0xf4, 0x1c, 0x20, 0x20, 0x82, 0x2c, 0x68, 0x24, 0x68, 0xa2, 0x81, 0x8d, 0x1d, 0xc9, 0x79,
	0xc3, 0x69, 0x22, 0xd8, 0x0d, 0x8d, 0x14, 0x85, 0x96, 0x5f, 0x6c, 0x48, 0xce, 0x09, 0x8d, 0x57,
	0xe1, 0x82, 0xb8, 0x75, 0xd5, 0x4f, 0x16, 0xe2, 0x21, 0xb4, 0x73, 0x46, 0x3c, 0x66, 0x11, 0xa7,
	0xe8, 0x10, 0x1a, 0x5c, 0x10, 0xb1, 0xe1, 0x9a, 0x94, 0x8e, 0xe4, 0xbe, 0xec, 0x29, 0x0c, 0xb4,
	0x26, 0x3a, 0xc2, 0x03, 0x68, 0xcb, 0xfb, 0xb3, 0x90, 0x8b, 0xac, 0xab, 0x12, 0x1b, 0xeb, 0x2f,
	0x36, 0xf8, 0x97, 0x05, 0x3b, 0xf2, 0xc6, 0x34, 0xba, 0x66, 0x46, 0x55, 0xcb, 0xac, 0x8a, 0x3c,
	0xd8, 0x91, 0x2b, 0x25, 0x4e, 0x2a, 0x44, 0x1e, 0xcb, 0x3b, 0x9b, 0x58, 0x7e, 0x11, 0x25, 0xc4,
	0x9e, 0xaf, 0x23, 0x84, 0x61, 0x77, 0x91, 0x50, 0xf5, 0x91, 0x03, 0x22, 0xa8, 0xd2, 0xc1, 0xf1,
	0x4b, 0x7b, 0x46, 0x77, 0xf5, 0x52, 0x77, 0x65, 0x81, 0x1b, 0x15, 0x81, 0x0d, 0x09, 0x9b, 0x65,
	0x09, 0x47, 0xd0, 0x29, 0xfa, 0xd7, 0x1a, 0x0e, 0xa0, 0x25, 0xd9, 0xf2, 0x30, 0xba, 0x66, 0xae,
	0xd5, 0xb3, 0xfb, 0x8f, 0xcf, 0xbb, 0xb9, 0x23, 0xb2, 0xde, 0xfd, 0x22, 0x07, 0x4f, 0xa1, 0x3b,
	0x22, 0xd1, 0x82, 0xae, 0x4c, 0x73, 0x3c, 0x28, 0xe3, 0xbd, 0xdf, 0xe3, 0x14, 0x90, 0x59, 0xea,
	0xe1, 0xaf, 0x8a, 0xbf, 0x40, 0xf7, 0x32, 0x96, 0xca, 0xfc, 0x37, 0x70, 0xee, 0x65, 0xdb, 0xf0,
	0xb2, 0x21, 0x9b, 0x53, 0x96, 0xed, 0x14, 0x90, 0x09, 0xfc, 0x0f, 0x9a, 0x53, 0xe8, 0xca, 0xbc,
	0x31, 0x15, 0x24, 0x5c, 0x65, 0x34, 0xef, 0x23, 0xf2, 0xb0, 0xfd, 0xfa, 0x80, 0xcc, 0x52, 0x1a,
	0x18, 0x81, 0x73, 0xc5, 0x82, 0xdb, 0xec, 0x21, 0xca, 0x35, 0xfe, 0x69, 0x81, 0x23, 0x53, 0xe5,
	0xe1, 0x5c, 0xbe, 0x48, 0x7d, 0x28, 0xd7, 0xf7, 0x82, 0x6b, 0xe3, 0xaa, 0x7c, 0xbb, 0x30, 0xae,
	0xba, 0x93, 0x29, 0xe4, 0x18, 0x0a, 0x1d, 0x40, 0x3d, 0x5c, 0xcb, 0x69, 0x92, 0xfa, 0x31, 0x0d,
	0x4c, 0xdd, 0x1a, 0x25, 0xdd, 0x64, 0x3e, 0xfd, 0x2a, 0x92, 0xd4, 0x86, 0x2d, 0x3f, 0x0d, 0xf0,
	0x2b, 0x00, 0xad, 0xe3, 0x66, 0x55, 0x9d, 0x68, 0x87, 0xd0, 0x48, 0xd4, 0x49, 0xc6, 0x35, 0x8d,
	0x4e, 0x5e, 0x43, 0x23, 0x1d, 0x4f, 0xa8, 0x09, 0xf6, 0x70, 0x3c, 0xee, 0x3c, 0x42, 0x00, 0x8d,
	0xd1, 0xf0, 0xed, 0x68, 0x32, 0xeb, 0x58, 0x72, 0x7d, 0xf9, 0x7e, 0x3c, 0x9c, 0x4f, 0x3a, 0x35,
	0xb4, 0x03, 0xce, 0x6c, 0xfa, 0x61, 0xde, 0xb1, 0xe5, 0xee, 0x78, 0x32, 0x1f, 0x4e, 0x67, 0x1d,
	0xe7, 0xfc, 0xce, 0x86, 0xa6, 0xc4, 0x7d, 0xb3, 0x4c, 0xd0, 0x25, 0x34, 0xf5, 0x28, 0x41, 0x47,
	0xb9, 0xd7, 0xcb, 0xe3, 0xce, 0x73, 0xab, 0x07, 0xa9, 0xfe, 0xf8, 0xe8, 0xdb, 0xef, 0xbb, 0x1f,
	0xb5, 0x2e, 0xde, 0xcd, 0x86, 0xf9, 0x80, 0x04, 0xc1, 0x85, 0x75, 0x82, 0x08, 0x40, 0x61, 0x67,
	0xe4, 0xe5, 0x05, 0x2a, 0xcf, 0xc5, 0x7b, 0xb6, 0xf5, 0x4c, 0xd7, 0xf7, 0x54, 0xfd, 0x03, 0xdc,
	0xce, 0xeb, 0x2f, 0x54, 0x92, 0x86, 0x28, 0xac, 0x68, 0x40, 0x54, 0x1e, 0x86, 0x01, 0x51, 0xf5,
	0xee, 0x16, 0x88, 0x8d, 0x4a, 0x92, 0x10, 0x1f, 0xd3, 0x91, 0x27, 0x87, 0x04, 0x72, 0x4b, 0x93,
	0xc0, 0x98, 0x9b, 0xde, 0xd3, 0x2d, 0x27, 0xba, 0xb8, 0xab, 0x8a, 0x23, 0xbc, 0x97, 0x17, 0x5f,
	0x85, 0x5c, 0x68, 0xf6, 0x85, 0x9f, 0x0d, 0xf6, 0x95, 0xf7, 0x62, 0xb0, 0xaf, 0x3e, 0x80, 0x2d,
	0xec, 0x03, 0x95, 0x70, 0x61, 0x9d, 0x5c, 0x35, 0xd4, 0x1f, 0xf3, 0xe5, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2b, 0xea, 0x34, 0x3a, 0x6f, 0x07, 0x00, 0x00,
}
