task:
	API_ADDRESS="localhost:50051" \
	MICRO_REGISTRY="mdns" \
	go run task.go

user:
	API_ADDRESS="localhost:50051" \
	MICRO_REGISTRY="mdns" \
	go run user.go

all:
	API_ADDRESS="localhost:50051" \
	MICRO_REGISTRY="mdns" \
	go run all.go
