// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dccenter.proto

package dccenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_88075538dcd2ca7c, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

// DataCenterList request message
type DataCenterListRequest struct {
	Usertoken            string   `protobuf:"bytes,1,opt,name=usertoken,proto3" json:"usertoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataCenterListRequest) Reset()         { *m = DataCenterListRequest{} }
func (m *DataCenterListRequest) String() string { return proto.CompactTextString(m) }
func (*DataCenterListRequest) ProtoMessage()    {}
func (*DataCenterListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88075538dcd2ca7c, []int{1}
}

func (m *DataCenterListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListRequest.Unmarshal(m, b)
}
func (m *DataCenterListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListRequest.Marshal(b, m, deterministic)
}
func (m *DataCenterListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListRequest.Merge(m, src)
}
func (m *DataCenterListRequest) XXX_Size() int {
	return xxx_messageInfo_DataCenterListRequest.Size(m)
}
func (m *DataCenterListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListRequest proto.InternalMessageInfo

func (m *DataCenterListRequest) GetUsertoken() string {
	if m != nil {
		return m.Usertoken
	}
	return ""
}

type DataCenterInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataCenterInfo) Reset()         { *m = DataCenterInfo{} }
func (m *DataCenterInfo) String() string { return proto.CompactTextString(m) }
func (*DataCenterInfo) ProtoMessage()    {}
func (*DataCenterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_88075538dcd2ca7c, []int{2}
}

func (m *DataCenterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterInfo.Unmarshal(m, b)
}
func (m *DataCenterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterInfo.Marshal(b, m, deterministic)
}
func (m *DataCenterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterInfo.Merge(m, src)
}
func (m *DataCenterInfo) XXX_Size() int {
	return xxx_messageInfo_DataCenterInfo.Size(m)
}
func (m *DataCenterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterInfo proto.InternalMessageInfo

func (m *DataCenterInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataCenterInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DataCenterListResponse struct {
	DcList               []*DataCenterInfo `protobuf:"bytes,1,rep,name=dcList,proto3" json:"dcList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataCenterListResponse) Reset()         { *m = DataCenterListResponse{} }
func (m *DataCenterListResponse) String() string { return proto.CompactTextString(m) }
func (*DataCenterListResponse) ProtoMessage()    {}
func (*DataCenterListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88075538dcd2ca7c, []int{3}
}

func (m *DataCenterListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListResponse.Unmarshal(m, b)
}
func (m *DataCenterListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListResponse.Marshal(b, m, deterministic)
}
func (m *DataCenterListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListResponse.Merge(m, src)
}
func (m *DataCenterListResponse) XXX_Size() int {
	return xxx_messageInfo_DataCenterListResponse.Size(m)
}
func (m *DataCenterListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListResponse proto.InternalMessageInfo

func (m *DataCenterListResponse) GetDcList() []*DataCenterInfo {
	if m != nil {
		return m.DcList
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "dccenter.Event")
	proto.RegisterType((*DataCenterListRequest)(nil), "dccenter.DataCenterListRequest")
	proto.RegisterType((*DataCenterInfo)(nil), "dccenter.DataCenterInfo")
	proto.RegisterType((*DataCenterListResponse)(nil), "dccenter.DataCenterListResponse")
}

func init() { proto.RegisterFile("proto/dccenter.proto", fileDescriptor_88075538dcd2ca7c) }

var fileDescriptor_88075538dcd2ca7c = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x49, 0x4e, 0x4e, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x03, 0x73, 0x85, 0x38, 0x60,
	0x7c, 0x29, 0x99, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xc4, 0xbc,
	0xbc, 0xfc, 0x92, 0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x88, 0x3a, 0x25, 0x76, 0x2e, 0x56, 0xd7,
	0xb2, 0xd4, 0xbc, 0x12, 0x25, 0x53, 0x2e, 0x51, 0x97, 0xc4, 0x92, 0x44, 0x67, 0xb0, 0x26, 0x9f,
	0xcc, 0xe2, 0x92, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x19, 0x2e, 0xce, 0xd2, 0xe2,
	0xd4, 0xa2, 0x92, 0xfc, 0xec, 0xd4, 0x3c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80,
	0x92, 0x09, 0x17, 0x1f, 0x42, 0x9b, 0x67, 0x5e, 0x5a, 0xbe, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x0a,
	0x58, 0x21, 0x73, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04,
	0x13, 0x58, 0x2b, 0x98, 0xad, 0xe4, 0xc5, 0x25, 0x86, 0x6e, 0x59, 0x71, 0x41, 0x7e, 0x5e, 0x71,
	0xaa, 0x90, 0x01, 0x17, 0x5b, 0x4a, 0x32, 0x48, 0x44, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48,
	0x42, 0x0f, 0xee, 0x31, 0x54, 0x7b, 0x82, 0xa0, 0xea, 0x8c, 0xaa, 0xb8, 0x38, 0x5c, 0xa0, 0x4a,
	0x84, 0xf2, 0x90, 0x5d, 0x03, 0x92, 0x15, 0x92, 0xc7, 0xa6, 0x1f, 0xc9, 0x7b, 0x52, 0x0a, 0xb8,
	0x15, 0x40, 0x9c, 0xa4, 0x24, 0xd9, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x61, 0x25, 0x3e, 0x78, 0x18,
	0xeb, 0xe7, 0x64, 0x16, 0x97, 0x58, 0x31, 0x6a, 0x25, 0xb1, 0x81, 0x03, 0xd1, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x7b, 0xfc, 0x36, 0x9e, 0x84, 0x01, 0x00, 0x00,
}
