// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dcmgr/dcmgr.proto

package go_micro_srv_dcmgr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcmgr_33cc1ff3844557a4, []int{0}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type All struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *All) Reset()         { *m = All{} }
func (m *All) String() string { return proto.CompactTextString(m) }
func (*All) ProtoMessage()    {}
func (*All) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcmgr_33cc1ff3844557a4, []int{1}
}
func (m *All) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_All.Unmarshal(m, b)
}
func (m *All) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_All.Marshal(b, m, deterministic)
}
func (dst *All) XXX_Merge(src proto.Message) {
	xxx_messageInfo_All.Merge(dst, src)
}
func (m *All) XXX_Size() int {
	return xxx_messageInfo_All.Size(m)
}
func (m *All) XXX_DiscardUnknown() {
	xxx_messageInfo_All.DiscardUnknown(m)
}

var xxx_messageInfo_All proto.InternalMessageInfo

// DataCenterList request message
type Request struct {
	UserToken            string   `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcmgr_33cc1ff3844557a4, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

type DataCenter struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataCenter) Reset()         { *m = DataCenter{} }
func (m *DataCenter) String() string { return proto.CompactTextString(m) }
func (*DataCenter) ProtoMessage()    {}
func (*DataCenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcmgr_33cc1ff3844557a4, []int{3}
}
func (m *DataCenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenter.Unmarshal(m, b)
}
func (m *DataCenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenter.Marshal(b, m, deterministic)
}
func (dst *DataCenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenter.Merge(dst, src)
}
func (m *DataCenter) XXX_Size() int {
	return xxx_messageInfo_DataCenter.Size(m)
}
func (m *DataCenter) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenter.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenter proto.InternalMessageInfo

func (m *DataCenter) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataCenter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataCenter) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcmgr_33cc1ff3844557a4, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ID)(nil), "go.micro.srv.dcmgr.ID")
	proto.RegisterType((*All)(nil), "go.micro.srv.dcmgr.All")
	proto.RegisterType((*Request)(nil), "go.micro.srv.dcmgr.Request")
	proto.RegisterType((*DataCenter)(nil), "go.micro.srv.dcmgr.DataCenter")
	proto.RegisterType((*Response)(nil), "go.micro.srv.dcmgr.Response")
}

func init() { proto.RegisterFile("proto/dcmgr/dcmgr.proto", fileDescriptor_dcmgr_33cc1ff3844557a4) }

var fileDescriptor_dcmgr_33cc1ff3844557a4 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xb7, 0x8d, 0xad, 0xee, 0x1c, 0x3c, 0x0c, 0xb2, 0x96, 0x45, 0x65, 0xc9, 0xa9, 0xa7,
	0x08, 0xfa, 0x03, 0x64, 0xb1, 0xe2, 0xee, 0xc1, 0x4b, 0xd0, 0xb3, 0xc4, 0x66, 0x28, 0xc5, 0x6d,
	0x53, 0x93, 0xa9, 0xff, 0xd5, 0x7f, 0x23, 0x1b, 0x15, 0x41, 0x17, 0x3c, 0x78, 0x09, 0xc9, 0xf7,
	0x5e, 0x1e, 0x6f, 0x18, 0x38, 0x1e, 0xbc, 0x63, 0x77, 0x6e, 0xeb, 0xae, 0xf1, 0x1f, 0xa7, 0x8a,
	0x04, 0xb1, 0x71, 0xaa, 0x6b, 0x6b, 0xef, 0x54, 0xf0, 0xaf, 0x2a, 0x2a, 0xf2, 0x08, 0xd2, 0x75,
	0x85, 0x87, 0x90, 0xb6, 0xb6, 0x48, 0x16, 0x49, 0x29, 0x74, 0xda, 0x5a, 0x99, 0x81, 0x58, 0x6e,
	0x36, 0xb2, 0x84, 0x7d, 0x4d, 0x2f, 0x23, 0x05, 0xc6, 0x53, 0x80, 0x31, 0x90, 0x7f, 0x64, 0xf7,
	0x4c, 0x7d, 0x74, 0x4e, 0xf5, 0x74, 0x4b, 0xee, 0xb7, 0x40, 0xae, 0x00, 0x2a, 0xc3, 0xe6, 0x9a,
	0x7a, 0x26, 0xff, 0x33, 0x0e, 0x11, 0xf6, 0x7a, 0xd3, 0x51, 0x91, 0xc6, 0x6f, 0xf1, 0x8e, 0x33,
	0xc8, 0x03, 0x1b, 0x1e, 0x43, 0x21, 0x16, 0x49, 0x99, 0xe9, 0xcf, 0x97, 0x04, 0x38, 0xd0, 0x14,
	0x06, 0xd7, 0x07, 0xba, 0x78, 0x4b, 0x20, 0xab, 0xea, 0xbb, 0xc6, 0xe3, 0x15, 0x88, 0x5b, 0x62,
	0x9c, 0xa9, 0xdf, 0x23, 0xa8, 0x75, 0x35, 0x3f, 0xdb, 0xc5, 0xbf, 0x0b, 0xc9, 0x09, 0xde, 0x80,
	0x58, 0x5a, 0x8b, 0x7f, 0x18, 0xe7, 0x27, 0xbb, 0xf4, 0xaf, 0x3e, 0x72, 0x82, 0x2b, 0xc8, 0x1f,
	0x06, 0x6b, 0x98, 0xfe, 0x9b, 0xf4, 0x94, 0xc7, 0x9d, 0x5c, 0xbe, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x86, 0xb0, 0xf9, 0x5b, 0xae, 0x01, 0x00, 0x00,
}
