apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consul
  labels:
    app: consul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:latest
        imagePullPolicy: Always
#        command: ["consul agent", "-dev -log-level=warn -ui -client=0.0.0.0"]
#        args: ["-dev -log-level=warn -ui -client=0.0.0.0"]
#        args: [
#          "-dev",
#          "-log-level=warn",
#          "-ui -client=0.0.0.0"
#        ]
        ports:
        - containerPort: 8300
        - containerPort: 8400
        - containerPort: 8500
        - containerPort: 53
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  ports:
    - name: "8300"
      port: 8300
      targetPort: 8300
    - name: "8400"
      port: 8400
      targetPort: 8400
    - name: "8500"
      port: 8500
      targetPort: 8500
    - name: "8600"
      port: 8600
      protocol: UDP
      targetPort: 53
  selector:
    app: consul
