apiVersion: v1
kind: Service
metadata:
  name: dccn-tendermint
  labels:
    app: dccn-tendermint
spec:
  selector:
    app: dccn-tendermint
  type: LoadBalancer
  ports:
  - name: p2p-1
    port: 20016
    targetPort: 26656
  - name: p2p-2
    port: 20026
    targetPort: 26656
  - name: p2p-3
    port: 20036
    targetPort: 26656
  - name: p2p-4
    port: 20046
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-tendermint-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dccn-tendermint
    spec:
      imagePullSecrets:
      - name: aws-ecr
      containers:
      - name: tendermint
        image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-tendermint:hub-feat
        imagePullPolicy: Always
        command: ["sh", "-c", "mv config/node_key.1.json config/node_key.json && mv config/priv_validator_key.1.json config/priv_validator_key.json && tendermint node --proxy_app=ankrchain --moniker=`hostname`"]
        ports:
        - name: p2p-1
          containerPort: 26656
        - name: rpc
          containerPort: 26657
        - name: abci
          containerPort: 26658

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-tendermint-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dccn-tendermint
    spec:
      imagePullSecrets:
      - name: aws-ecr
      containers:
      - name: tendermint
        image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-tendermint:hub-feat
        imagePullPolicy: Always
        command: ["sh", "-c", "mv config/node_key.2.json config/node_key.json && mv config/priv_validator_key.2.json config/priv_validator_key.json && tendermint node --proxy_app=ankrchain --moniker=`hostname`"]
        ports:
        - name: p2p-2
          containerPort: 26656
        - name: rpc
          containerPort: 26657
        - name: abci
          containerPort: 26658

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-tendermint-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dccn-tendermint
    spec:
      imagePullSecrets:
      - name: aws-ecr
      containers:
      - name: tendermint
        image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-tendermint:hub-feat
        imagePullPolicy: Always
        command: ["sh", "-c", "mv config/node_key.3.json config/node_key.json && mv config/priv_validator_key.3.json config/priv_validator_key.json && tendermint node --proxy_app=ankrchain --moniker=`hostname`"]
        ports:
        - name: p2p-3
          containerPort: 26656
        - name: rpc
          containerPort: 26657
        - name: abci
          containerPort: 26658

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-tendermint-4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dccn-tendermint
    spec:
      imagePullSecrets:
      - name: aws-ecr
      containers:
      - name: tendermint
        image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-tendermint:hub-feat
        imagePullPolicy: Always
        command: ["sh", "-c", "mv config/node_key.4.json config/node_key.json && mv config/priv_validator_key.4.json config/priv_validator_key.json && tendermint node --proxy_app=ankrchain --moniker=`hostname`"]
        ports:
        - name: p2p-4
          containerPort: 26656
        - name: rpc
          containerPort: 26657
        - name: abci
          containerPort: 26658
