// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account.proto

package accountmgr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{1}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Account struct {
	//    name unique as mongodb _id
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Balance              uint32   `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetBalance() uint32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type Accounts struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Accounts) Reset()         { *m = Accounts{} }
func (m *Accounts) String() string { return proto.CompactTextString(m) }
func (*Accounts) ProtoMessage()    {}
func (*Accounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{3}
}

func (m *Accounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accounts.Unmarshal(m, b)
}
func (m *Accounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accounts.Marshal(b, m, deterministic)
}
func (m *Accounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accounts.Merge(m, src)
}
func (m *Accounts) XXX_Size() int {
	return xxx_messageInfo_Accounts.Size(m)
}
func (m *Accounts) XXX_DiscardUnknown() {
	xxx_messageInfo_Accounts.DiscardUnknown(m)
}

var xxx_messageInfo_Accounts proto.InternalMessageInfo

func (m *Accounts) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Response struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{5}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{6}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "accountmgr.Empty")
	proto.RegisterType((*Name)(nil), "accountmgr.Name")
	proto.RegisterType((*Account)(nil), "accountmgr.Account")
	proto.RegisterType((*Accounts)(nil), "accountmgr.Accounts")
	proto.RegisterType((*Response)(nil), "accountmgr.Response")
	proto.RegisterType((*Token)(nil), "accountmgr.Token")
	proto.RegisterType((*Error)(nil), "accountmgr.Error")
}

func init() { proto.RegisterFile("proto/account.proto", fileDescriptor_477cbf5ae5b46edf) }

var fileDescriptor_477cbf5ae5b46edf = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0x26, 0x4d, 0xd2, 0xc4, 0x53, 0x2f, 0x78, 0xe7, 0x5e, 0x30, 0x04, 0x17, 0x61, 0x36, 0x56,
	0xc1, 0x06, 0xea, 0x4e, 0x71, 0x71, 0x17, 0xb5, 0xb8, 0xb0, 0x8b, 0x20, 0x2e, 0x85, 0x69, 0x32,
	0xc4, 0xd0, 0x64, 0x26, 0xcc, 0x4c, 0x2d, 0x6e, 0x05, 0x9f, 0xc0, 0x97, 0xf1, 0x3d, 0x7c, 0x05,
	0x1f, 0x44, 0xe6, 0x27, 0x6d, 0xc4, 0x16, 0xbc, 0xbb, 0xf9, 0xbe, 0x73, 0xbe, 0x8f, 0xf3, 0x9d,
	0x93, 0xc0, 0x4d, 0x2f, 0xb8, 0xe2, 0x39, 0x29, 0x4b, 0xbe, 0x67, 0x6a, 0x61, 0x10, 0x02, 0x07,
	0xbb, 0x5a, 0xa4, 0x4f, 0x6a, 0xce, 0xeb, 0x96, 0xe6, 0xa4, 0x6f, 0x72, 0xc2, 0x18, 0x57, 0x44,
	0x35, 0x9c, 0x49, 0xdb, 0x89, 0x23, 0x08, 0x57, 0x5d, 0xaf, 0xbe, 0xe2, 0x14, 0x82, 0x0d, 0xe9,
	0x28, 0x42, 0x10, 0x30, 0xd2, 0xd1, 0xc4, 0xcb, 0xbc, 0xf9, 0x83, 0xc2, 0xbc, 0xf1, 0x77, 0x0f,
	0xa2, 0x3b, 0xeb, 0x78, 0xac, 0x4f, 0x4e, 0x75, 0x94, 0x42, 0xcc, 0x9a, 0x72, 0x67, 0xf8, 0xc0,
	0xf0, 0x47, 0x8c, 0x6e, 0x21, 0xa4, 0x1d, 0x69, 0xda, 0x24, 0x34, 0x05, 0x0b, 0xb4, 0xa2, 0x27,
	0x52, 0x1e, 0xb8, 0xa8, 0x92, 0xa9, 0x55, 0x0c, 0x18, 0x25, 0x10, 0x6d, 0x49, 0x4b, 0x58, 0x49,
	0x93, 0x28, 0xf3, 0xe6, 0x57, 0xc5, 0x00, 0xf1, 0x6b, 0x88, 0xdd, 0x18, 0x12, 0xe5, 0x10, 0xbb,
	0x90, 0x32, 0xf1, 0x32, 0x7f, 0x3e, 0x5b, 0xde, 0x2c, 0x4e, 0xa9, 0x17, 0xae, 0xaf, 0x38, 0x36,
	0xe1, 0x2d, 0xc4, 0x05, 0x95, 0x3d, 0x67, 0x92, 0xa2, 0x17, 0x10, 0x39, 0xde, 0xe4, 0xbc, 0xa0,
	0x1d, 0x7a, 0xd0, 0x53, 0x08, 0xa9, 0x10, 0x5c, 0x98, 0xd0, 0xb3, 0xe5, 0xf5, 0xb8, 0x79, 0xa5,
	0x0b, 0x85, 0xad, 0xe3, 0x4f, 0x10, 0x7e, 0xe0, 0x3b, 0xca, 0x74, 0x6a, 0xa5, 0x1f, 0x6e, 0x8d,
	0x16, 0x68, 0xf6, 0x0b, 0x69, 0x9b, 0xca, 0xf8, 0xc4, 0x85, 0x05, 0xe8, 0x19, 0x4c, 0x8d, 0x5a,
	0x26, 0xbe, 0xc9, 0x71, 0xc6, 0xde, 0x35, 0xe0, 0x37, 0x10, 0x1a, 0x42, 0x5f, 0xa1, 0xe4, 0x95,
	0xbd, 0x52, 0x58, 0x98, 0x37, 0xca, 0x60, 0x56, 0x51, 0x59, 0x8a, 0xa6, 0xd7, 0x07, 0x76, 0x07,
	0x1a, 0x53, 0xcb, 0x9f, 0x13, 0x00, 0x17, 0xee, 0x7d, 0x2d, 0xd0, 0x3b, 0xf0, 0x37, 0xf4, 0x80,
	0xce, 0x65, 0x4f, 0x6f, 0xc7, 0xe4, 0xb0, 0x37, 0xfc, 0xf8, 0xdb, 0xaf, 0xdf, 0x3f, 0x26, 0xd7,
	0xf8, 0xe1, 0xf0, 0xbd, 0xe5, 0x8c, 0x1e, 0x5e, 0x79, 0xcf, 0xd1, 0x5b, 0xf0, 0xd7, 0x54, 0xa1,
	0x47, 0x63, 0x95, 0xfe, 0x9c, 0xfe, 0xdb, 0xa7, 0xa6, 0x4a, 0xfb, 0xac, 0x21, 0xb8, 0xdb, 0xab,
	0xcf, 0xe7, 0x67, 0xfa, 0x6b, 0x31, 0x66, 0xcf, 0x97, 0x07, 0xda, 0xc0, 0xd5, 0x47, 0xbd, 0x5d,
	0xa2, 0xa8, 0xbd, 0xc8, 0xbf, 0xe2, 0xfb, 0xf8, 0x6d, 0xa7, 0xe6, 0x77, 0x79, 0xf9, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xce, 0xfd, 0x76, 0x51, 0x6f, 0x03, 0x00, 0x00,
}
