// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/v1/dcmgr.proto

/*
Package go_micro_srv_v1_dcmgr is a generated protocol buffer package.

It is generated from these files:
	proto/v1/dcmgr.proto

It has these top-level messages:
	ID
	DataCenter
	Response
*/
package go_micro_srv_v1_dcmgr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DcMgr service

type DcMgrService interface {
	//    Get gets a DataCenter by ID
	Get(ctx context.Context, in *ID, opts ...client.CallOption) (*DataCenter, error)
	Create(ctx context.Context, in *DataCenter, opts ...client.CallOption) (*Response, error)
}

type dcMgrService struct {
	c    client.Client
	name string
}

func NewDcMgrService(name string, c client.Client) DcMgrService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.v1.dcmgr"
	}
	return &dcMgrService{
		c:    c,
		name: name,
	}
}

func (c *dcMgrService) Get(ctx context.Context, in *ID, opts ...client.CallOption) (*DataCenter, error) {
	req := c.c.NewRequest(c.name, "DcMgr.Get", in)
	out := new(DataCenter)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcMgrService) Create(ctx context.Context, in *DataCenter, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DcMgr.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DcMgr service

type DcMgrHandler interface {
	//    Get gets a DataCenter by ID
	Get(context.Context, *ID, *DataCenter) error
	Create(context.Context, *DataCenter, *Response) error
}

func RegisterDcMgrHandler(s server.Server, hdlr DcMgrHandler, opts ...server.HandlerOption) error {
	type dcMgr interface {
		Get(ctx context.Context, in *ID, out *DataCenter) error
		Create(ctx context.Context, in *DataCenter, out *Response) error
	}
	type DcMgr struct {
		dcMgr
	}
	h := &dcMgrHandler{hdlr}
	return s.Handle(s.NewHandler(&DcMgr{h}, opts...))
}

type dcMgrHandler struct {
	DcMgrHandler
}

func (h *dcMgrHandler) Get(ctx context.Context, in *ID, out *DataCenter) error {
	return h.DcMgrHandler.Get(ctx, in, out)
}

func (h *dcMgrHandler) Create(ctx context.Context, in *DataCenter, out *Response) error {
	return h.DcMgrHandler.Create(ctx, in, out)
}
