// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/usermgr/usermgr.proto

package go_micro_api_usermgr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_9113063ee25a1fa1, []int{0}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type User struct {
	// id self-increase
	Id *ID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name should be unique
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// nickname show on UI
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// email user's email
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// password string
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	// balance user's balance in account
	Balance int32 `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	// is_deleted user's status
	IsDeleted            bool     `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_9113063ee25a1fa1, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *User) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_9113063ee25a1fa1, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type TokenString struct {
	TokenString          string   `protobuf:"bytes,1,opt,name=token_string,json=tokenString,proto3" json:"token_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenString) Reset()         { *m = TokenString{} }
func (m *TokenString) String() string { return proto.CompactTextString(m) }
func (*TokenString) ProtoMessage()    {}
func (*TokenString) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_9113063ee25a1fa1, []int{3}
}
func (m *TokenString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenString.Unmarshal(m, b)
}
func (m *TokenString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenString.Marshal(b, m, deterministic)
}
func (dst *TokenString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenString.Merge(dst, src)
}
func (m *TokenString) XXX_Size() int {
	return xxx_messageInfo_TokenString.Size(m)
}
func (m *TokenString) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenString.DiscardUnknown(m)
}

var xxx_messageInfo_TokenString proto.InternalMessageInfo

func (m *TokenString) GetTokenString() string {
	if m != nil {
		return m.TokenString
	}
	return ""
}

func init() {
	proto.RegisterType((*ID)(nil), "go.micro.api.usermgr.ID")
	proto.RegisterType((*User)(nil), "go.micro.api.usermgr.User")
	proto.RegisterType((*Response)(nil), "go.micro.api.usermgr.Response")
	proto.RegisterType((*TokenString)(nil), "go.micro.api.usermgr.TokenString")
}

func init() {
	proto.RegisterFile("proto/usermgr/usermgr.proto", fileDescriptor_usermgr_9113063ee25a1fa1)
}

var fileDescriptor_usermgr_9113063ee25a1fa1 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xbd, 0x4e, 0xf3, 0x40,
	0x10, 0x8c, 0x9d, 0x3f, 0x67, 0xfd, 0xe9, 0x2b, 0x56, 0x29, 0x4e, 0x46, 0x20, 0xc7, 0x95, 0x2b,
	0x83, 0x42, 0x4d, 0x81, 0x88, 0x84, 0x22, 0x04, 0xc5, 0xf1, 0xd3, 0x46, 0x4e, 0x6e, 0xb1, 0x4e,
	0x89, 0x7d, 0xd6, 0x9d, 0x51, 0xc4, 0x4b, 0xf1, 0x22, 0xbc, 0x14, 0xf2, 0x99, 0x04, 0x0a, 0x93,
	0x54, 0xf6, 0xcc, 0xec, 0xac, 0x76, 0x46, 0x07, 0x27, 0xa5, 0x56, 0x95, 0x3a, 0x7f, 0x33, 0xa4,
	0xf3, 0x4c, 0xef, 0xbe, 0x89, 0x65, 0x71, 0x9c, 0xa9, 0x24, 0x97, 0x2b, 0xad, 0x92, 0xb4, 0x94,
	0xc9, 0xb7, 0x16, 0x8d, 0xc1, 0x9d, 0xcf, 0xf0, 0x3f, 0xb8, 0x52, 0x30, 0x27, 0x74, 0xe2, 0x2e,
	0x77, 0xa5, 0x88, 0x3e, 0x1d, 0xe8, 0x3d, 0x1b, 0xd2, 0x18, 0xef, 0x05, 0x7f, 0xca, 0x92, 0xb6,
	0x0d, 0xc9, 0x7c, 0x56, 0x5b, 0x10, 0xa1, 0x57, 0xa4, 0x39, 0x31, 0x37, 0x74, 0xe2, 0x11, 0xb7,
	0xff, 0x18, 0x80, 0x57, 0xc8, 0xd5, 0xda, 0xf2, 0x3d, 0xcb, 0xef, 0x31, 0x8e, 0xa1, 0x4f, 0x79,
	0x2a, 0x37, 0xac, 0x6f, 0x85, 0x06, 0xd4, 0x8e, 0x32, 0x35, 0x66, 0xab, 0xb4, 0x60, 0x83, 0xc6,
	0xb1, 0xc3, 0xc8, 0x60, 0xb8, 0x4c, 0x37, 0x69, 0xb1, 0x22, 0x36, 0x0c, 0x9d, 0xb8, 0xcf, 0x77,
	0x10, 0x4f, 0x01, 0xa4, 0x59, 0x08, 0xda, 0x50, 0x45, 0x82, 0x79, 0xa1, 0x13, 0x7b, 0x7c, 0x24,
	0xcd, 0xac, 0x21, 0x22, 0x00, 0x8f, 0x93, 0x29, 0x55, 0x61, 0x28, 0xba, 0x00, 0xff, 0x49, 0xad,
	0xa9, 0x78, 0xac, 0xb4, 0x2c, 0x32, 0x9c, 0xc0, 0xbf, 0xaa, 0x86, 0x0b, 0x63, 0xb1, 0x4d, 0x3a,
	0xe2, 0x7e, 0xf5, 0x33, 0x32, 0xfd, 0x70, 0x61, 0x58, 0x77, 0x71, 0x9f, 0x69, 0xbc, 0x81, 0xee,
	0xb5, 0x10, 0x18, 0xb4, 0x37, 0x51, 0x4f, 0x05, 0x67, 0xed, 0xda, 0xfe, 0x80, 0x0e, 0x5e, 0x41,
	0xf7, 0x96, 0x2a, 0xfc, 0xb3, 0xce, 0xe0, 0xc0, 0xfa, 0xa8, 0x83, 0x77, 0xe0, 0x3d, 0xd0, 0xd6,
	0x86, 0x38, 0x78, 0xc8, 0xa4, 0x5d, 0xfb, 0x95, 0x3e, 0xea, 0x20, 0x07, 0xff, 0x85, 0xb4, 0x7c,
	0x7d, 0x6f, 0xf6, 0x1d, 0xf7, 0x1c, 0xcf, 0xb7, 0x1c, 0xd8, 0xf7, 0x76, 0xf9, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x6a, 0x6d, 0x6d, 0x37, 0x8e, 0x02, 0x00, 0x00,
}
